### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jab375** [olixr/MudPi#7]
I been following the step by step guide found here https://mudpi.app/guides/8 . When I run the mudpi.py i receive the following output. Is the Server error normal? I rebuilt the PI twice now with the same result.

`Initializing Garden Control...           Complete
Preparing Threads for Workers...         Complete
No Camera Found to Load
Humidity Sensor (Pi) 25...               Ready
Loading Pi Sensor Worker...
Pi Sensor Worker [2 Sensors]...          Running
No Relays Found to Load
Traceback (most recent call last):
  File "mudpi.py", line 144, in <module>
    for relay in CONFIGS['relays']:
KeyError: 'relays'
Invalid or no Nodes found to Load
Traceback (most recent call last):
  File "mudpi.py", line 167, in <module>
    for node in CONFIGS['nodes']:
KeyError: 'nodes'
No Actions Found to Load
Traceback (most recent call last):
  File "mudpi.py", line 191, in <module>
    for action in CONFIGS["actions"]:
KeyError: 'actions'
No Triggers Found to Load
Traceback (most recent call last):
  File "mudpi.py", line 201, in <module>
    t = TriggerWorker(CONFIGS['triggers'], main_thread_running, system_ready, actions)
KeyError: 'triggers'
MudPi Shutting Down...                   Starting
Traceback (most recent call last):
  File "mudpi.py", line 216, in <module>
    server = MudpiServer(main_thread_running, CONFIGS['server']['host'], CONFIGS['server']['port'])
KeyError: 'server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mudpi.py", line 247, in <module>
    server.sock.shutdown(socket.SHUT_RDWR)
NameError: name 'server' is not defined
`

**Comment by jab375** [comment]
I found a installer script. I think your Mudpi.app website it out of date on raspberry pi setup.
